//@ui5-bundle masterfrontend/Component-preload.js
sap.ui.require.preload({
	"masterfrontend/Component.js":function(){
sap.ui.define(["sap/suite/ui/generic/template/lib/AppComponent"],function(e){"use strict";return e.extend("masterfrontend.Component",{metadata:{manifest:"json"}})});
},
	"masterfrontend/changes/flexibility-bundle.json":'{"changes":[{"fileName":"id_1698900818535_2_propertyChange","fileType":"change","changeType":"propertyChange","moduleName":"","reference":"masterfrontend","packageName":"","content":{"property":"liveMode","newValue":false},"selector":{"id":"masterfrontend::sap.suite.ui.generic.template.ListReport.view.ListReport::MASTER_001--listReportFilter","idIsLocal":false,"type":"sap.ui.comp.smartfilterbar.SmartFilterBar"},"layer":"CUSTOMER_BASE","texts":{},"namespace":"apps/masterfrontend/changes/","projectId":"","creation":1698900843435,"originalLanguage":"","support":{"generator":"changeUtils: SAPFioriTools","service":"","user":"","sapui5Version":"1.119.2","sourceChangeFileName":"","compositeCommand":""},"oDataInformation":{},"dependentSelector":{},"validAppVersions":{"from":"0.0.1","to":"0.0.1","creation":"0.0.1"},"jsOnly":false,"variantReference":"","appDescriptorChange":false}],"compVariants":[],"variants":[],"variantChanges":[],"variantDependentControlChanges":[],"variantManagementChanges":[]}',
	"masterfrontend/i18n/i18n.properties":'# This is the resource bundle for masterfrontend\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=\\u6309\\u5206\\u30a8\\u30e9\\u30fc\\u4e00\\u89a7\\u753b\\u9762\n\n#YDES: Application description\nappDescription=A Fiori application.\n\nflpTitle=\\u6309\\u5206\\u30a8\\u30e9\\u30fc\\u4e00\\u89a7\\u753b\\u9762\n',
	"masterfrontend/manifest.json":'{"_version":"1.58.0","sap.app":{"id":"masterfrontend","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:lrop","version":"1.11.3","toolsId":"fe733e8b-599a-4c00-be94-0255f4bcc1b5"},"dataSources":{"mainService":{"uri":"odata/v2/MasterService/","type":"OData","settings":{"annotations":["annotation"],"localUri":"localService/metadata.xml","odataVersion":"2.0"}},"annotation":{"type":"ODataAnnotation","uri":"annotations/annotation.xml","settings":{"localUri":"annotations/annotation.xml"}}},"crossNavigation":{"inbounds":{"nykmaster01-display":{"semanticObject":"nykmaster01","action":"display","title":"{{flpTitle}}","signature":{"parameters":{},"additionalParameters":"allowed"}}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.119.2","libs":{"sap.m":{},"sap.ui.core":{},"sap.ushell":{},"sap.f":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.suite.ui.generic.template":{},"sap.ui.fl":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"masterfrontend.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{"defaultBindingMode":"TwoWay","defaultCountMode":"Inline","refreshAfterChange":false,"useBatch":false,"metadataUrlParams":{"sap-value-list":"none"}}},"@i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"}},"resources":{"css":[]},"routing":{"config":{},"routes":[],"targets":{}}},"sap.ui.generic.app":{"_version":"1.3.0","settings":{"forceGlobalRefresh":false,"objectPageHeaderType":"Dynamic","considerAnalyticalParameters":true,"showDraftToggle":false},"pages":{"ListReport|MASTER_001":{"entitySet":"MASTER_001","component":{"name":"sap.suite.ui.generic.template.ListReport","list":true,"settings":{"condensedTableLayout":true,"smartVariantManagement":true,"enableTableFilterInPageVariant":true,"filterSettings":{"dateSettings":{"useDateRange":true}},"dataLoadSettings":{"loadDataOnAppLaunch":"always"}}},"pages":{"ObjectPage|MASTER_001":{"entitySet":"MASTER_001","defaultLayoutTypeIfExternalNavigation":"MidColumnFullScreen","component":{"name":"sap.suite.ui.generic.template.ObjectPage"}}}}}},"sap.fiori":{"registrationIds":[],"archeType":"transactional"},"sap.cloud":{"public":true,"service":"masterfrontend"}}'
});
//# sourceMappingURL=Component-preload.js.map
