GET http://localhost:8080/odata/v2/MasterService/MASTER_001			
Content-Type: application/json				

###
PUT http://localhost:8080/odata/v2/MasterService/MASTER_001	
Content-Type: application/json

{
    "companyCode":"1001",
    "fiscalYear":"2022",
    "fiscalPeriod":"05",
    "sequence":"111233",
    "generalLedger":"34444222",
    "vessel":"GGH",
    "textStr ":"XXXXXXXX",
    "occurrenceDate":"2023-11-02",
    "slipNo":"22222",
    "slipDetailNo":"001",
    "domesticCurrencyAmount":1234,
    "resultMessage":"FFDDDDDDD",
    "createUser":"LIYANG",
    "createDate":"2023-11-02T11:10:00.000Z",
    "createPGM":"TEST",
    "updateUser":"LIYANG",
    "updateDate":"2023-11-02T11:10:00.000Z",,
    "updatePGM":"TEST",
    "deleteFlg":false
}